apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
        - name: chatbot
          image: chatbot:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: LLM_URL
              value: http://host.minikube.internal:11434/v1/chat/completions
            - name: LLM_MODEL
              value: llama3:latest
              